### ISSUE TITLE
jQuery UI collision

### ISSUE THREAD

**Issue by vojtasvoboda** [surahmans/blogtags#2]
When I install a plugin, then open detail of blog post at backend and switch to Settings tab, I can see calendar icon placed on the left submenu (under last menu item).

![snimek obrazovky 2016-03-12 v 17 28 41](https://cloud.githubusercontent.com/assets/374917/13724048/08b3c94a-e879-11e5-8e8d-84cabe5efa5b.png)

It is problem with this line https://github.com/surahmans/blogtags/blob/master/formwidgets/tagbox/assets/css/jquery-ui-1.8.2.custom.css#L10

But without this line, autocomplete show some status line on the bottom of the whole page.

Second thing is many bugs in console, mainly some missing images from jQuery UI.

**Comment by surahmans** [comment]
Hi @vojtasvoboda ,
Sorry but I can't reproduce your issue.

**Comment by vojtasvoboda** [comment]
Uhm, you are right, seems like to be an issue with old OctoberCMS version, sorry for false issue
