### ISSUE TITLE
Error when uninstalling

### ISSUE THREAD

**Issue by vojtasvoboda** [surahmans/blogtags#3]
![snimek obrazovky 2016-03-16 v 17 38 45](https://cloud.githubusercontent.com/assets/374917/13821046/3e69aa1c-eba0-11e5-8063-1063501b1f42.png)

**Comment by CoryWA** [comment]
Same Issue.

**Comment by surahmans** [comment]
Thank you @vojtasvoboda and @CoryWA.
This issue has been [fixed](https://github.com/surahmans/blogtags/commit/093ee3e48b8710c280bd3ec1037472d22657cf1b).
