### ISSUE TITLE
Bug with removed tags not being able to be added again.

### ISSUE THREAD

**Issue by joejordanbrown** [surahmans/blogtags#6]
When you remove a tag you previously added and try to add again you are unable to i think this is to do with the getData and then not using updateURL to update the tags on the server. 

I also noticed that it was case sensitive which can be an issue. I've made a pull request on the js plugin which you can find here https://github.com/ioncache/Tag-Handler/pull/40 which adds the option "caseSensitive" type "bool" defaults to true so would need to be false for case insensitive.

Would you consider changing to a different input tag plugin since this one doesn't seem to be maintained and is very limited on functionality. You can't edit the tag once its been entered etc.

**Comment by surahmans** [comment]
I have updated using taglist field from octoberCMS core.
